name: "horoscope_app"
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  carousel_slider: ^4.0.0 # Correctly aligned dependency
  curved_navigation_bar: ^1.0.6
  postgres: ^2.0.0
  http: ^1.2.2 # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/stars_background.jpg
    - assets/png-image.png
    - assets/text.png
    - assets/earth.png
    - assets/logo-image.png
    - assets/arrow_back.png
    - assets/quill_calendar.png
    - assets/sun.png
    - assets/mars.png
    - assets/sugar.png
    - assets/saturn.png
    - assets/sanchir.png
    - assets/barhasbadi.png
    - assets/moon.png
    - assets/menu/today.png
    - assets/menu/month.png
    - assets/menu/hoslol.png
    - assets/menu/orduud.png
    - assets/menu/profile.png

flutter_native_splash:
  background_image: "assets/stars_background.jpg" # Set the background image for all devices
  color: "#000000" # Optional fallback color (set to black or any other complementary color)

  android_12:
    image: "assets/logo-image.png" # Center image for Android 12+
    background_image: "assets/stars_background.jpg" # Background image for Android 12+
